import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from config import load_config

LECTURE_MARKER = "[FROM LECTURE]"
SLIDES_MARKER = "[FROM SLIDES]"


def _ever_existed_in_git(vault_path: Path, path: Path) -> bool:
    """True if `path` shows up anywhere in the vault's git history, even if
    it's been deleted from the working tree since. This vault's sync routine
    deletes transcript_raw.md files after the fact, so on-disk existence
    can't be trusted as "was this ever transcribed" — git history can.
    Degrades to False (never crashes) if git or the repo isn't available.
    """
    try:
        result = subprocess.run(
            ["git", "log", "--all", "--oneline", "--", str(path.relative_to(vault_path))],
            cwd=vault_path,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return result.returncode == 0 and bool(result.stdout.strip())


@dataclass
class TopicStatus:
    course: str
    week: int
    topic: str
    transcribed: bool
    enhanced: bool
    cleaned: bool
    slides_enhanced: bool
    has_flashcards: bool
    has_exam_questions: bool


def _week_number(week_dir_name: str) -> int:
    """'Week 3' -> 3. Unparsable names sort last instead of crashing."""
    for part in reversed(week_dir_name.split()):
        if part.isdigit():
            return int(part)
    return 10**6


def scan_topics(vault_path: Path, semester: str) -> list[TopicStatus]:
    """Walk every <Course>/Week N/<NN - Title>.md under the semester folder and
    derive pipeline status from the vault's files and git history.

    Detection is inherently limited: `cleanup` strips [FROM LECTURE] /
    [FROM SLIDES] markers by design, so a topic that was enhanced then cleaned
    looks identical, from marker text alone, to one that was cleaned without
    ever being enhanced. `enhanced` is cumulative with `cleaned` (a cleaned
    topic counts as enhanced, since enhance is a mandatory step cleanup
    always follows) — this can't catch the rare case of a transcript sitting
    untouched next to an already-clean note. `slides_enhanced` is NOT
    cumulative with `cleaned`, because slides-enhance is optional and
    parallel rather than a mandatory prerequisite — it only reflects the
    literal marker, so it goes dark for good once a topic is cleaned without
    ever having been slides-enhanced. `transcribed` falls back to git history
    rather than trusting on-disk existence alone, since transcript_raw.md
    files get deleted from this vault after the fact.
    """
    semester_dir = vault_path / semester
    rows: list[TopicStatus] = []

    for topic_path in sorted(semester_dir.glob("*/Week */*.md")):
        course = topic_path.parent.parent.name
        week = _week_number(topic_path.parent.name)
        topic = topic_path.stem
        sibling_dir = topic_path.with_suffix("")
        text = topic_path.read_text(encoding="utf-8")

        transcript_path = sibling_dir / "transcript_raw.md"
        transcribed = transcript_path.exists() or _ever_existed_in_git(vault_path, transcript_path)
        cleaned = transcribed and LECTURE_MARKER not in text
        enhanced = cleaned or LECTURE_MARKER in text
        # Not cumulative with cleaned, unlike `enhanced`: slides-enhance is an
        # optional, parallel step, not a mandatory one cleanup always follows.
        # Treating it as implied-by-cleaned would hide it from the reminder
        # list forever on every topic that skips it entirely.
        slides_enhanced = SLIDES_MARKER in text

        rows.append(
            TopicStatus(
                course=course,
                week=week,
                topic=topic,
                transcribed=transcribed,
                enhanced=enhanced,
                cleaned=cleaned,
                slides_enhanced=slides_enhanced,
                has_flashcards=(sibling_dir / "flashcards.md").exists(),
                has_exam_questions=(sibling_dir / "exam_questions.md").exists(),
            )
        )

    rows.sort(key=lambda r: (r.course, r.week, r.topic))
    return rows


def _mark(value: bool) -> str:
    return "✅" if value else "⬜"


def render_report(rows: list[TopicStatus], semester: str) -> str:
    lines = [
        f"# Progress — {semester}",
        "",
        "Regenerated by `scripts/progress.py` from the vault's own files — don't hand-edit, rerun instead.",
        "`Enhanced`/`Slides-enhanced` count as done once `Cleaned` is true, since cleanup erases the marker that would otherwise prove it.",
        "",
        "## Core pipeline",
        "",
        "| Course | Week | Topic | Transcribed | Enhanced | Cleaned |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r.course} | {r.week} | {r.topic} | {_mark(r.transcribed)} | {_mark(r.enhanced)} | {_mark(r.cleaned)} |"
        )

    lines += [
        "",
        "## Enrichment (reminders)",
        "",
        "| Course | Week | Topic | Slides-enhanced | Flashcards |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r.course} | {r.week} | {r.topic} | {_mark(r.slides_enhanced)} | {_mark(r.has_flashcards)} |"
        )

    lines += [
        "",
        "> [!NOTE]- Exam prep (review-notes) — closer to exam time",
        "> | Course | Week | Topic | Exam questions |",
        "> |---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"> | {r.course} | {r.week} | {r.topic} | {_mark(r.has_exam_questions)} |")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Regenerate the semester progress tracker from the vault")
    parser.add_argument("semester", help='Semester folder name under the vault, e.g. "3. Semester"')
    args = parser.parse_args(argv)

    try:
        config = load_config()
        vault_path = Path(config["VAULT_PATH"])
    except FileNotFoundError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
    except KeyError:
        print("Missing config key: VAULT_PATH", file=sys.stderr)
        sys.exit(1)

    rows = scan_topics(vault_path, args.semester)
    if not rows:
        print(f"No topic notes found under {vault_path / args.semester}", file=sys.stderr)
        sys.exit(1)

    output_path = vault_path / args.semester / "Progress.md"
    output_path.write_text(render_report(rows, args.semester), encoding="utf-8")

    done = sum(1 for r in rows if r.cleaned)
    print(f"Wrote {output_path} — {done}/{len(rows)} topics cleaned")


if __name__ == "__main__":
    main()
